#################################
# General setup
#################################
language: python

sudo: false

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
before_install:
  - echo "----- before_install -----"

install:
  - echo "----- install -----"
  # Make sure I'm in the correct directory after all that before_install crap
  - cd /home/travis/build/dougthor42/wafer_map/

  # Start the install of everything
  - pip install --upgrade pip
  - pip install http://dougthor42.github.io/tools/wxPython-3.0.3-cp34-cp34m-linux_x86_64.whl
  - pip install green
  - pip install coverage
  - pip install colour
  - pip install colorama
    pip install numpy
    pip install coveralls
    pip install wheel

script:
  - echo "----- script -----"
  - green wafer_map -vv --run-coverage

after_success:
  - echo "----- after_success -----"

  # Send coverage information to coveralls.io
  - coveralls
