#################################
# General setup
#################################
language: python

sudo: required

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
before_install:
  - echo "-----before_install-----"

  # Installing wxPython Phoenix from source
  #------------------------------------------
  # Download the source tarball
  - wget http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz
  - ls

  # extract it
  - tar -xzf wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz
  - ls
  - ls wxPython_Phoenix-3.0.3.dev1820+49a8884

  # Run the build script
  - ls ./wxPython_Phoenix-3.0.3.dev1820+49a8884/
  - cd ./wxPython_Phoenix-3.0.3.dev1820+49a8884
  - ls
#  - python build.py --help
#  - python ./build.py 3.4 --build_dir=../bld --nodoc dox etg sip build
  - sudo python ./build.py 3.4 dox touch etg --nodoc sip build
  - python ./build.py 3.4 test --verbose
  - cd ..

install:
  - echo "-----install-----"
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install wheel
  - pip install numpy
  #- pip install "wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz"
#  - pip install --upgrade --pre --trusted-host wxpython.org -vvv -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

script:
  - nosetests
  - python --version

#################################
# Additional Items
#################################
addons:
  apt:
    packages:
      - libghc-gstreamer-dev
      - dpkg-dev
#      - libnotify
      - libsdl1.2-dev

      # For wxPython?
      - dpkg-dev
      - build-essential
#      - python2.7-dev # use appropriate Python version
      - libwebkitgtk-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk2.0-dev
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - freeglut3-dev
