#################################
# General setup
#################################
language: python

sudo: false

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################

before_install:
  - echo "----- before_install -----"
  - echo "Installing wxPython Phoenix from repo clone"
  # Clone the repo (downloads entire history)
  - git clone --depth=50 --branch=master git://github.com/wxWidgets/Phoenix.git

  # Change to the directory
  - cd Phoenix

  # Have to get submodule wxWidgets. See README.rts:building-wxwidgets
  - git submodule init
  - git submodule update

  # Switch to the correct commit:
#  - echo "Using commit # 49a8884e7c"
#  - git checkout 49a8884e7c

  # Build wxPython from source.
  - python ./build.py dox
  - python ./build.py build_wx
  - python ./build.py touch
  - python ./build.py etg --nodoc
  - python ./build.py sip
  - python ./build.py build_py

install:
  - echo "----- install -----"
  # Make sure I'm in the correct directory after all that before_install crap
  - cd /home/travis/build/dougthor42/wafer_map/

  # Start the install of everything
  - pip install --upgrade pip

script:
  - echo "----- script -----"
#  - nosetests
  - python --version

#################################
# Additional Items
#################################
addons:
#  artifacts: true

  apt:
    packages:
      - libghc-gstreamer-dev
      - libnotify

      # For wxPython?
      - dpkg-dev
      - build-essential
      - libwebkitgtk-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk2.0-dev
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - freeglut3-dev
      - libnotify-dev
