#################################
# General setup
#################################
language: python

sudo: false

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
before_install:
  - echo "-----before_install-----"

  # Installing wxPython Phoenix from source
  #------------------------------------------
  # Download the source tarball
  - wget http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz
  - mv wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz wxPython_Phoenix-3.0.3.tar.gz

  # extract it
  - tar -xzf wxPython_Phoenix-3.0.3.tar.gz

  # Run the build script
  - ls ./wxPython_Phoenix-3.0.3/wxPython/
  - python ./wxPython_Phoenix-3.0.3/wxPython/build-wxpython.py --install

install:
  - echo "-----install-----"
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install wheel
  - pip install numpy
  #- pip install "wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz"
#  - pip install --upgrade --pre --trusted-host wxpython.org -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

script:
  - nosetests
  - python --version

addons:
  apt:
    packages:
      - libghc-gstreamer-dev
      - dpkg-dev
      - libnotify
      - libsdl1.2-dev