language: python

sudo: required

python:
  - "2.7"

notifications:
  email: False

before_install:
  - echo "-----before_install-----"
  # get Conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a


install:
  - echo "-----install-----"
  # Install wxPython
  - conda install -c https://conda.anaconda.org/travis wxpython
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install wheel
  #- pip install "wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz"
  #- sudo pip install --upgrade --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

# command to run tests
script:
  #- nosetests
  - python --version
