language: python

sudo: required

python:
  - "2.7"

notifications:
  email: False

# command to install dependencies
before_install:
  # Method 1
  - "sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n libwxgtk2.8-dev libgtk2.0-dev"

  # Method 2
  #- sudo apt-get install python-wxgtk2.8
  #- wget "http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz"
  #- tar -xzf wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz
  #- ls
  #- cd wxPython_Phoenix-3.0.3.dev1820+49a8884
  #- ls
  #- sudo add-apt-repository -y ppa:gstreamer-developers/ppa
  #- sudo apt-get update
  #- sudo apt-get install gstreamer1.0*
  #- sudo apt-get install libgstreamer0.10-dev
  #- python setup.py build
  #- python setup.py install
  #- cd ..
  
  # Method 3
  #- sudo apt-get install dpkg-dev build-essential
  #- sudo apt-get install libjpeg-dev libtiff-dev
  #- sudo apt-get install libgtk2.0-dev
  #- sudo apt-get install libsdl1.2-dev libgstreamer-plugins-base0.10-dev 
  
  # Method 4
  #- sudo apt-get install libgl1-mesa-glx libglu1-mesa libgl1-mesa-dev libglu1-mesa-dev libgstreamer0.10-dev libgconf2-dev libsdl1.2-dev zlib1g-dev libjpeg62-dev libtiff4-dev python-gst0.10-dev
    

install:
  - pip install --upgrade
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install wheel
  #- pip install "wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz"
  #- sudo pip install --upgrade --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

# command to run tests
script:
  #- nosetests
  - python --version
