#################################
# General setup
#################################
language: python

sudo: false

matrix:
  include:
    # Before I can run this on Travis-CI, I need to make a wheel for linux
#  - python: "2.7"
#    env:
#      - WXPYTHON=http://dougthor42.github.io/tools/wxPython-3.0.3-cp34-cp34m-linux_x86_64.whl
  - python: "3.4"
    env:
      - WXPYTHON=http://dougthor42.github.io/tools/wxPython-3.0.3-cp34-cp34m-linux_x86_64.whl


notifications:
  email: false

#################################
# Build Lifecycle
#################################
before_install:
  - echo "----- before_install -----"

install:
  - echo "----- install -----"

  # Start the install of everything
  - pip install --upgrade pip
  - pip install WXPYTHON
  - pip install green
  - pip install coverage
  - pip install colour
  - pip install colorama
  - pip install numpy
  - pip install coveralls
  - pip install wheel

script:
  - echo "----- script -----"
  - green wafer_map -vv --run-coverage

after_success:
  - echo "----- after_success -----"

  # Send coverage information to coveralls.io
  - coveralls
