### ----------------------
### General Configuration
### ----------------------

environment:
  global:
    WXPYTHON_SNAPSHOTS: "https://wxpython.org/Phoenix/snapshot-builds"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.13"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.13"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe --version"

  # install dependencies
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install wheel"
  #- "%PYTHON%\\python.exe -m pip install %WXPYTHON%"
  - "%PYTHON%\\python.exe -m pip install --only-binary :all: --pre -f %WXPYTHON_SNAPSHOTS% wxPython_Phoenix"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"

build: off  # Not a C# project, build stuff at the test step instead.

test_script:
  # Build the compiled extension and run the project tests
  - "%PYTHON%\\python.exe --version"
  - "pytest -ra wafer_map --cov wafer_map --cov-report term"

after_test:
  # if tests OK, create whl package
  - "%PYTHON%\\python.exe setup.py sdist bdist_wheel"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*.whl
